### ISSUE TITLE
Access multiple FlashAir cards simultaneously

### ISSUE THREAD

**Issue by dentphoto** [emoacht/SnowyImageCopy#41]
Hi, Emoacht !

I have two flashair cards(Sta mode) on two digital cameras.
Two Snowy app windows are opened on the PC and each card successfully transmit images wirelessly .
Like the attached photo...
Is it possible that the Snowy app supports multiple cards in an integrated way in the future?
Without opening two or more Snowy app windows...

![2 digicam + 2 card](https://user-images.githubusercontent.com/60927347/79045053-0d3ddd80-7c44-11ea-9bf7-6781cebd1892.jpg)

**Comment by emoacht** [comment]
Thanks for your suggestion.
The current version is not designed to run multiple instances simultaneously. You can start multiple instances simultaneously, it is simply because doing so is not prevented internally, but the settings file and other files which this app creates will be shared within multiple instances. It may cause some unexpected behaviors.
At the same time, I understand the need to access multiple FlashAir cards simultaneously. I am currently working on the next version targeted for Microsoft Store which can open multiple windows for each FlashAir card. I believe that a window for a card is better than a window for multiple cards because it will be too complex and hard to manage.

**Comment by dentphoto** [comment]
Thank you.
I look forward to the multiple card support version.

**Comment by emoacht** [comment]
The new version becomes available at Microsoft Store.
