### ISSUE TITLE
Overwrite image of the same file name with different file size

### ISSUE THREAD

**Issue by dentphoto** [emoacht/SnowyImageCopy#44]
This situation sometimes occurs.
Several files from D5600 are already in the local folder.
eg) DSC_8797.JPG   DSC_8798.JPG   DSC_8799.JPG   DSC_8800.JPG

When a picture taken on another D3200 is transferred, the existing file is automatically overwritten.
Although the file name is the same, the picture content and file size are completely different...
As a result, the first 4 photos of D5600 are disappearing forever.

## Description on YouTube : http://youtu.be/ldOYSxq-Y-0

If the name of the file in the local folder is the same but the file size is different, it is reasonable to rename and transfer as follows.
eg) DSC_8797-1.JPG   DSC_8798-1.JPG   DSC_8799-1.JPG   DSC_8800-1.JPG

Is it technically possible?
For reference, in the same situation the previous eye-fi sd renames the files and transferred.

**Comment by emoacht** [comment]
This behavior is intentional.
It is for overwriting a file corrupted during the previous copy. To be honest, I have not expected that anyone may risk their files by using the same local folder when a file name can be duplicated.
I recommend not to specify the same local folder in such case in the first place. But it can happen accidentally. So I add setting not to overwrite existing files.
https://github.com/emoacht/SnowyImageCopy/commit/25093ecc61606e9514b71a7794beb5d575c7396f https://github.com/emoacht/SnowyImageCopy/commit/e90ea92831b8a1aa44b39c4a69cb457f5460b35a
Please note the number of same file name files are limited to 65535.
